Repository Goorm-Lucky7/ThinkTank_FE, pull requests merged in 2024-05, with the labels that each got.

#27 [PR] 상세 페이지 UI 구현
  src/assets/images/defaultUser.png
  src/components/detail/commentItem/index.tsx
  src/components/detail/commentItem/styles.ts
  src/components/detail/detailDescBox/index.tsx
  src/components/detail/detailDescBox/styles.ts
  src/components/detail/detailTestCase/index.tsx
  src/components/detail/detailTestCase/styles.ts
  src/components/detail/index.ts
  src/components/mainComp/mainExtra/MainExtra.tsx
  src/components/mainComp/mainList/MainList.tsx
  src/components/mainComp/mainList/MainListItem/index.tsx
  src/components/post/index.ts
  src/components/post/postDescBox/index.tsx
  src/components/post/postDescBox/styles.ts
  src/components/post/testCaseBox/index.tsx
  src/components/post/textareaField/styles.ts
  src/components/shared/CodeEditor.tsx
  src/components/shared/Icon.tsx
  src/components/shared/Text.tsx
  src/components/shared/UserCircle.tsx
  src/components/shared/article/index.tsx
  src/components/shared/comment/index.tsx
  src/components/shared/icon/index.tsx
  src/components/shared/icon/styles.ts
  src/components/shared/index.ts
  src/components/shared/likes/index.tsx
  src/components/shared/modal/alertComponent/index.tsx
  src/components/shared/modal/alertComponent/styles.ts
  src/components/shared/modal/commentComponent/index.tsx
  src/components/shared/modal/commentComponent/styles.ts
  src/components/shared/modal/index.tsx
  src/components/shared/modal/styles.ts
  src/components/shared/pass/index.tsx
  src/contexts/ModalContext.tsx
  src/hooks/useLike.ts
  src/pages/detail/index.tsx
  src/pages/detail/left/index.tsx
  src/pages/detail/left/styles.ts
  src/pages/detail/right/index.tsx
  src/pages/detail/right/styles.ts
  src/pages/detail/styles.ts
  src/pages/error/index.tsx
  src/pages/index.ts
  src/pages/post/left/index.tsx
  src/pages/post/right/index.tsx
  src/routes/index.ts
  src/styles/colorPalette.ts
  src/styles/globalStyles.ts
  src/types/comment.ts
  src/types/user.ts
  src/utils/getTimeDifference.ts
Labels: bug, enhancement

#25 [PR] jwt 인증 구현
  src/apis/AuthAPI.ts
  src/components/loginForm/index.tsx
  src/components/shared/inputBox/index.tsx
  src/components/signup/optionalForm/index.tsx
  src/components/signup/optionalForm/styles.ts
  src/components/signup/signupForm/index.tsx
  src/hooks/useForm.ts
  src/stores/signupStore.ts
  src/stores/userStore.ts
  src/types/auth.ts
  src/types/user.ts
Labels: enhancement

#26 [PR] 전체 게시글 조회 기능 구현
  pnpm-lock.yaml
  src/apis/index.ts
  src/apis/like/index.ts
  src/apis/main/index.ts
  src/components/mainComp/mainExtra/MainExtra.tsx
  src/components/mainComp/mainExtra/styles.ts
  src/components/mainComp/mainList/MainList.tsx
  src/components/mainComp/mainList/MainListData.ts
  src/components/mainComp/mainList/MainListItem/index.tsx
  src/components/mainComp/mainList/MainListItem/styles.ts
  src/components/nav/Nav.tsx
  src/components/nav/navItems.ts
  src/components/nav/styles.ts
  src/components/shared/article/index.tsx
  src/components/shared/article/styles.ts
  src/components/shared/comment/index.tsx
  src/components/shared/icon/index.tsx
  src/components/shared/icon/styles.ts
  src/components/shared/index.ts
  src/components/shared/infoStatus/index.tsx
  src/components/shared/infoStatus/styles.ts
  src/components/shared/likes/index.tsx
  src/components/shared/likes/styles.ts
  src/components/shared/pass/index.tsx
  src/hooks/like/useLike.ts
  src/hooks/useLike.ts
  src/main.tsx
  src/routes/protectedRoute.ts
  src/types/article.ts
Labels: enhancement

#34 Develop/detailpart
  package.json
  pnpm-lock.yaml
  src/components/detail/commentItem/index.tsx
  src/components/detail/detailDescBox/index.tsx
  src/components/detail/detailDescBox/styles.ts
  src/components/detail/detailTestCase/index.tsx
  src/components/detail/index.ts
  src/components/mainComp/mainExtra/MainExtra.tsx
  src/components/post/index.ts
  src/components/post/postDescBox/index.tsx
  src/components/post/posttestCaseBox/index.tsx
  src/components/post/posttestCaseBox/styles.ts
  src/components/post/textareaField/styles.ts
  src/components/shared/descriptionBox/index.tsx
  src/components/shared/descriptionBox/styles.ts
  src/components/shared/index.ts
  src/components/shared/modal/index.tsx
  src/components/shared/select/index.tsx
  src/components/shared/select/styles.ts
  src/components/shared/testCaseBox/index.tsx
  src/components/shared/testCaseBox/styles.ts
  src/contexts/ModalContext.tsx
  src/hooks/post/useSetFormData.ts
  src/hooks/useGetPathname.ts
  src/pages/detail/left/index.tsx
  src/pages/detail/right/index.tsx
  src/pages/post/left/index.tsx
  src/pages/post/right/index.tsx
  src/types/post.ts
Labels: enhancement

#36 [PR] 배포 테스트
  Dockerfile
  goorm.manifest
  k8s/deployment.yaml
  k8s/ingress.yaml
  k8s/kustomization.yaml
  k8s/service.yaml
Labels: enhancement

#40 [PR] auth api 수정
  src/apis/authAxios.ts
  src/apis/like/index.ts
  src/apis/main/index.ts
  src/apis/mypage.ts
  src/apis/refresh.ts
  src/apis/userapi.ts
  src/components/loginForm/index.tsx
  src/components/mypage/userInfo/index.tsx
  src/components/nav/navItems.ts
  src/components/shared/StyledButton.ts
Labels: bug

#44 [PR] 디테일 및 글 작성 페이지 API 만들기
  Dockerfile
  k8s/configs/default.conf
  k8s/frontend.yaml
  k8s/ingress.yaml
  k8s/kustomization.yaml
  k8s/nginx.yaml
  package.json
  pnpm-lock.yaml
  src/apis/authAxios.ts
  src/apis/comment.ts
  src/apis/post.ts
  src/components/detail/commentList/index.tsx
  src/components/detail/commentList/styles.ts
  src/components/detail/index.ts
  src/components/loader/circleLoader/index.tsx
  src/components/loader/circleLoader/styles.ts
  src/components/loginForm/index.tsx
  src/components/post/codeBox/index.tsx
  src/components/post/posttestCaseBox/index.tsx
  src/components/shared/CodeEditor.tsx
  src/components/shared/descriptionBox/index.tsx
  src/components/shared/modal/commentComponent/index.tsx
  src/components/shared/modal/commentComponent/styles.ts
  src/components/shared/select/index.tsx
  src/components/shared/testCaseBox/index.tsx
  src/consts/category.ts
  src/consts/defaultCode.ts
  src/hooks/post/useGetPost.ts
  src/hooks/withSuspense.tsx
  src/pages/detail/left/DetailFallback.tsx
  src/pages/detail/left/index.tsx
  src/pages/detail/left/styles.ts
  src/pages/detail/right/index.tsx
  src/pages/post/right/index.tsx
  src/stores/post.ts
  src/styles/framerMotion.ts
  src/styles/layout.ts
  src/types/post.ts
  src/utils/getCodeEditorOptions.ts
Labels: enhancement

#43 [PR] 공통 UI 컴포넌트 조정
  src/apis/authAxios.ts
  src/apis/mypage.ts
  src/apis/userapi.ts
  src/components/loginForm/index.tsx
  src/components/loginForm/styles.ts
  src/components/mypage/tabMenu/styles.ts
  src/components/mypage/userInfo/index.tsx
  src/components/mypage/userInfo/styles.ts
  src/components/nav/Nav.tsx
  src/components/nav/styles.ts
  src/components/shared/StyledButton.ts
  src/components/shared/icon/index.tsx
  src/hooks/useInfinity.ts
  src/pages/mypage/index.tsx
  src/pages/mypage/styles.ts
  src/pages/post/right/index.tsx
  src/pages/post/right/styles.ts
  src/styles/fonts.ts
  src/styles/layout.ts
  src/styles/typography.ts
Labels: documentation, enhancement

#47 [PR] api 수정, 마이페이지 게시글 조회
  src/apis/authAxios.ts
  src/apis/mypage.ts
  src/apis/post.ts
  src/apis/refresh.ts
  src/apis/userapi.ts
  src/components/loginForm/index.tsx
  src/components/mypage/created/index.tsx
  src/components/mypage/created/styles.ts
  src/components/mypage/liked/index.tsx
  src/components/mypage/profileTable/index.tsx
  src/components/mypage/profileTable/styles.ts
  src/components/mypage/solved/index.tsx
  src/components/mypage/tabMenu/index.tsx
  src/components/mypage/userInfo/index.tsx
  src/components/nav/navItems.ts
  src/components/shared/icon/index.tsx
  src/components/signup/optionalForm/index.tsx
  src/components/signup/signupForm/index.tsx
  src/hooks/useInfinity.ts
  src/pages/mypage/index.tsx
  src/pages/mypage/profile/index.tsx
  src/pages/mypage/profile/styles.ts
  src/routes/index.ts
  src/stores/mypage.ts
  src/stores/userStore.ts
  src/types/auth.ts
  src/types/mypage.ts
Labels: enhancement

#49 [PR] 메인 게시글 조회 및 좋아요
  package.json
  src/components/detail/commentItem/index.tsx
  src/hooks/like/useLike.ts
Labels: enhancement

#54 [PR] api, 마이페이지 수정 및 리팩토링
  src/apis/auth.ts
  src/apis/instance.ts
  src/apis/mypage.ts
  src/apis/user.ts
  src/components/loginForm/index.tsx
  src/components/loginForm/styles.ts
  src/components/mypage/articles/index.tsx
  src/components/mypage/articles/styles.ts
  src/components/mypage/index.ts
  src/components/mypage/liked/index.tsx
  src/components/mypage/solved/index.tsx
  src/components/mypage/tabMenu/index.tsx
  src/components/mypage/userInfo/index.tsx
  src/components/shared/article/index.tsx
  src/components/signup/optionalForm/index.tsx
  src/components/signup/optionalForm/styles.ts
  src/pages/mypage/profile/index.tsx
  src/stores/mypage.ts
  src/types/mypage.ts
Labels: documentation, enhancement

#57 Develop/mainquery
  pnpm-lock.yaml
  src/apis/authAxios.ts
  src/apis/like.ts
  src/apis/post.ts
  src/apis/refresh.ts
  src/components/loginForm/index.tsx
  src/components/main/MainListItem/index.tsx
  src/components/main/MainListItem/styles.ts
  src/components/main/mainExtra/styles.ts
  src/components/main/mainList/MainList.tsx
  src/components/main/mainList/styles.ts
  src/components/nav/styles.ts
  src/components/shared/article/index.tsx
  src/components/shared/article/styles.ts
  src/components/shared/icon/index.tsx
  src/components/shared/infoStatus/index.tsx
  src/hooks/like/useLike.ts
  src/hooks/post/useGetPost.ts
  src/hooks/post/useGetPosts.ts
  src/hooks/post/useSetFormData.ts
  src/pages/detail/right/index.tsx
  src/pages/main/index.tsx
  src/pages/main/styles.ts
  src/pages/post/right/index.tsx
  src/types/article.ts
Labels: enhancement

#63 [PR] 메인 마무리 및 라우트 강화
  src/App.tsx
  src/apis/auth.ts
  src/apis/authAxios.ts
  src/apis/instance.ts
  src/apis/refresh.ts
  src/components/loader/skeleton/index.tsx
  src/components/loader/skeleton/styles.ts
  src/components/main/MainListItem/index.tsx
  src/components/main/MainListItem/styles.ts
  src/components/main/mainExtra/MainExtra.tsx
  src/components/main/mainExtra/styles.ts
  src/components/main/mainList/MainList.tsx
  src/components/main/mainList/styles.ts
  src/components/mypage/userInfo/index.tsx
  src/components/nav/Nav.tsx
  src/components/nav/styles.ts
  src/components/shared/Text.tsx
  src/components/shared/article/index.tsx
  src/components/shared/article/styles.ts
  src/components/shared/icon/index.tsx
  src/components/shared/icon/styles.ts
  src/components/shared/infoStatus/index.tsx
  src/components/shared/infoStatus/styles.ts
  src/pages/main/index.tsx
  src/routes/protectedRoute.ts
  src/routes/protectedRoute.tsx
  src/styles/button.ts
  src/styles/layout.ts
  src/styles/typography.ts
Labels: enhancement

#62 [PR] 유저 프로필
  src/apis/auth.ts
  src/apis/instance.ts
  src/apis/mypage.ts
  src/apis/user.ts
  src/components/loginForm/index.tsx
  src/components/mypage/articles/index.tsx
  src/components/mypage/liked/index.tsx
  src/components/mypage/profileTable/index.tsx
  src/components/mypage/solved/SolvedBox.tsx
  src/components/mypage/solved/index.tsx
  src/components/mypage/solved/styles.ts
  src/components/mypage/tabMenu/index.tsx
  src/components/mypage/tabMenu/styles.ts
  src/components/mypage/userInfo/index.tsx
  src/components/signup/optionalForm/index.tsx
  src/components/signup/signupForm/index.tsx
  src/components/signup/signupForm/styles.ts
  src/hooks/auth/useLocalStorage.ts
  src/pages/mypage/index.tsx
  src/pages/mypage/profile/index.tsx
  src/types/auth.ts
  src/types/mypage.ts
Labels: documentation, enhancement

#61 [PR] 전체 마무리 및 댓글 기능 구현
  pnpm-lock.yaml
  src/App.tsx
  src/apis/article.ts
  src/apis/auth.ts
  src/apis/instance.ts
  src/apis/user.ts
  src/components/post/codeBox/index.tsx
  src/components/shared/CodeEditor.tsx
  src/components/shared/ErrorBoundary.tsx
  src/components/shared/descriptionBox/index.tsx
  src/components/shared/index.ts
  src/components/shared/modal/index.tsx
  src/components/shared/modal/questionComponent/indext.tsx
  src/components/shared/select/index.tsx
  src/components/signup/signupForm/index.tsx
  src/contexts/ModalContext.tsx
  src/hooks/post/useSetFormData.ts
  src/main.tsx
  src/pages/detail/right/index.tsx
  src/pages/main/index.tsx
  src/routes/index.ts
  src/stores/post.ts
  src/types/article.ts
  src/utils/getCode.ts
Labels: enhancement

#67 [Deploy] version 0.9
  src/App.css
  src/apis/like.ts
  src/components/shared/ErrorBoundary.tsx
  src/components/shared/Text.tsx
  src/hooks/detail/useGetComments.ts
  src/hooks/detail/useMutateComment.ts
  src/hooks/like/useLike.ts
  src/pages/detail/left/DetailFallback.tsx
  src/pages/post/right/styles.ts
Labels: enhancement

#71 [PR] 게시글 설정 UI 및 기능 구현
  src/apis/article.ts
  src/components/main/MainListItem/index.tsx
  src/components/main/MainListItem/styles.ts
  src/components/main/mainExtra/MainExtra.tsx
  src/components/main/mainExtra/styles.ts
  src/components/main/mainList/MainList.tsx
  src/components/main/mainList/styles.ts
  src/components/nav/Nav.tsx
  src/components/nav/styles.ts
  src/components/shared/StyledButton.ts
  src/components/shared/article/index.tsx
  src/components/shared/article/styles.ts
  src/components/shared/icon/index.tsx
  src/components/shared/infoStatus/index.tsx
  src/components/shared/modal/index.tsx
  src/components/shared/modal/settingComponent/index.tsx
  src/components/shared/modal/settingComponent/styles.ts
  src/consts/navItems.ts
  src/pages/main/styles.ts
  src/routes/protectedRoute.tsx
  src/styles/button.ts
  src/styles/media.ts
Labels: enhancement

#73 [PR] 유저 페이지 관련 수정
  src/apis/mypage.ts
  src/apis/user.ts
  src/components/loginForm/index.tsx
  src/components/mypage/articles/index.tsx
  src/components/mypage/articles/styles.ts
  src/components/mypage/profileTable/index.tsx
  src/components/mypage/profileTable/styles.ts
  src/components/mypage/solved/SolvedBox.tsx
  src/components/mypage/solved/index.tsx
  src/components/mypage/solved/styles.ts
  src/components/mypage/tabMenu/index.tsx
  src/components/mypage/userInfo/index.tsx
  src/components/mypage/userInfo/styles.ts
  src/components/shared/icon/index.tsx
  src/components/signup/optionalForm/index.tsx
  src/components/signup/signupForm/index.tsx
  src/consts/navItems.ts
  src/pages/mypage/profile/index.tsx
  src/pages/mypage/profile/styles.ts
  src/pages/mypage/styles.ts
  src/pages/signup/optional/index.tsx
  src/routes/index.ts
  src/types/auth.ts
Labels: enhancement

#72 [PR] 1차 UI test 개선 및 comment 구현
  src/App.tsx
  src/apis/article.ts
  src/apis/auth.ts
  src/apis/comment.ts
  src/apis/instance.ts
  src/components/detail/commentItem/index.tsx
  src/components/detail/commentItem/styles.ts
  src/components/detail/commentList/index.tsx
  src/components/post/posttestCaseBox/index.tsx
  src/components/post/posttestCaseBox/styles.ts
  src/components/post/tesCaseItem/index.tsx
  src/components/post/tesCaseItem/styles.ts
  src/components/post/textareaField/index.tsx
  src/components/shared/ErrorBoundary.tsx
  src/components/shared/Text.tsx
  src/components/shared/icon/index.tsx
  src/components/shared/modal/commentComponent/index.tsx
  src/components/shared/select/styles.ts
  src/components/shared/testCaseBox/index.tsx
  src/contexts/ModalContext.tsx
  src/hooks/detail/useGetComments.ts
  src/hooks/detail/useMutateComment.ts
  src/main.tsx
  src/pages/detail/left/DetailFallback.tsx
  src/pages/detail/right/index.tsx
  src/pages/detail/right/styles.ts
  src/pages/post/right/index.tsx
Labels: enhancement

#81 [PR] 삭제 기능 수정
  src/components/main/mainList/MainList.tsx
  src/components/mypage/articles/index.tsx
  src/components/nav/styles.ts
  src/components/shared/article/index.tsx
  src/components/shared/modal/index.tsx
  src/components/shared/modal/settingComponent/index.tsx
  src/styles/media.ts
Labels: bug

#84 [PR] 작은 오류 및 ui 수정
  README.md
  src/components/main/mainList/MainList.tsx
  src/components/mypage/articles/index.tsx
  src/components/mypage/solved/index.tsx
  src/components/mypage/userInfo/index.tsx
  src/components/nav/Nav.tsx
  src/pages/mypage/styles.ts
Labels: enhancement

#85 [Deploy] version 1.1
  README.md
  src/components/loginForm/index.tsx
  src/components/main/MainListItem/index.tsx
  src/components/mypage/articles/index.tsx
  src/components/mypage/articles/styles.ts
  src/components/mypage/solved/index.tsx
  src/components/mypage/solved/styles.ts
  src/components/mypage/tabMenu/styles.ts
  src/components/mypage/userInfo/index.tsx
  src/components/mypage/userInfo/styles.ts
  src/components/nav/Nav.tsx
  src/components/nav/styles.ts
  src/components/shared/ErrorBoundary.tsx
  src/components/shared/article/index.tsx
  src/components/shared/descriptionBox/index.tsx
  src/components/shared/modal/index.tsx
  src/components/shared/modal/settingComponent/index.tsx
  src/hooks/like/useLike.ts
  src/pages/detail/right/index.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/styles.ts
  src/pages/post/right/index.tsx
  src/styles/media.ts
  src/utils/getCategoryName.ts
Labels: enhancement
