Repository Goorm-Lucky7/ThinkTank_FE, pull requests merged in 2024-04, with the labels that each got.

#7 initial settings
  .gitignore
  thinktank/.eslintrc.cjs
  thinktank/.gitignore
  thinktank/.prettierignore
  thinktank/.prettierrc
  thinktank/README.md
  thinktank/eslint.config.js
  thinktank/index.html
  thinktank/package.json
  thinktank/pnpm-lock.yaml
  thinktank/public/vite.svg
  thinktank/src/App.css
  thinktank/src/App.tsx
  thinktank/src/assets/react.svg
  thinktank/src/index.css
  thinktank/src/main.tsx
  thinktank/src/vite-env.d.ts
  thinktank/tsconfig.json
  thinktank/tsconfig.node.json
  thinktank/vite.config.ts
Labels: enhancement

#13 [PR] 모달창 구현
  README.md
  eslint.config.js
  index.html
  src/components/post/descriptonBox/index.tsx
  src/components/post/descriptonBox/styles.ts
  src/components/post/index.ts
  src/components/post/testCaseBox/index.tsx
  src/components/post/testCaseBox/styles.ts
  src/components/shared/Icon.tsx
  src/components/shared/ShadowBox.tsx
  src/components/shared/Text.tsx
  src/components/shared/index.ts
  src/components/shared/modal/Dimmed.tsx
  src/components/shared/modal/index.tsx
  src/components/shared/modal/styles.ts
  src/consts/post.ts
  src/contexts/ModalContext.tsx
  src/main.tsx
  src/pages/index.ts
  src/pages/post/index.tsx
  src/pages/post/left/index.tsx
  src/pages/post/left/styles.ts
  src/pages/post/right/index.tsx
  src/pages/post/right/styles.ts
  src/routes/index.ts
  src/styles/colorPalette.ts
  src/styles/globalStyles.ts
  src/styles/typography.ts
  tsconfig.json
Labels: bug, documentation, enhancement

#14 [PR] 회원가입 UI 구현
  package.json
  src/components/optionalForm/index.tsx
  src/components/optionalForm/styles.ts
  src/components/shared/authBackground/index.tsx
  src/components/shared/authBackground/styles.ts
  src/components/shared/index.ts
  src/components/shared/inputBox/index.tsx
  src/components/shared/inputBox/styles.ts
  src/components/signupForm/index.tsx
  src/components/signupForm/styles.ts
  src/pages/index.ts
  src/pages/signup/index.tsx
  src/pages/signup/optional/index.tsx
  src/pages/signup/required/index.tsx
  src/routes/index.ts
  src/types/user.ts
  tsconfig.json
  vite.config.ts
Labels: bug, enhancement

#16 [PR] 문제 생성 좌측 영역 UI 및 기능
  README.md
  package.json
  pnpm-lock.yaml
  src/components/optionalForm/index.tsx
  src/components/post/codeBox/index.tsx
  src/components/post/codeBox/styles.ts
  src/components/post/descriptonBox/index.tsx
  src/components/post/descriptonBox/styles.ts
  src/components/post/index.ts
  src/components/post/languageSelect/index.tsx
  src/components/post/testCaseBox/index.tsx
  src/components/post/testCaseBox/styles.ts
  src/components/post/textareaField/index.tsx
  src/components/post/textareaField/styles.ts
  src/components/shared/CodeEditor.tsx
  src/components/shared/Icon.tsx
  src/components/shared/Line.tsx
  src/components/shared/ShadowBox.tsx
  src/components/shared/icon/index.tsx
  src/components/shared/icon/styles.ts
  src/components/shared/index.ts
  src/components/shared/select/index.tsx
  src/components/shared/select/styles.ts
  src/components/signupForm/index.tsx
  src/consts/category.ts
  src/consts/language.ts
  src/pages/index.ts
  src/pages/post/left/styles.ts
  src/pages/post/right/index.tsx
  src/pages/post/right/styles.ts
  src/styles/globalStyles.ts
  src/styles/layout.ts
  src/styles/typography.ts
Labels: bug, documentation, enhancement

#17 [PR] 회원가입 UI 구현
  pnpm-lock.yaml
  src/components/optionalForm/index.tsx
  src/components/optionalForm/styles.ts
  src/components/shared/StyledButton.ts
  src/components/shared/authBackground/styles.ts
  src/components/shared/icon/index.tsx
  src/components/shared/index.ts
  src/components/shared/inputBox/index.tsx
  src/components/shared/inputBox/styles.ts
  src/components/signup/optionalForm/index.tsx
  src/components/signup/optionalForm/styles.ts
  src/components/signup/signupForm/index.tsx
  src/components/signup/signupForm/styles.ts
  src/components/signupForm/index.tsx
  src/components/signupForm/styles.ts
  src/pages/signup/optional/index.tsx
  src/pages/signup/required/index.tsx
  src/styles/fonts.ts
  src/styles/layout.ts
Labels: enhancement

#19 [PR] 마이페이지 UI 구현
  src/components/mypage/index.ts
  src/components/mypage/tabMenu/index.tsx
  src/components/mypage/userInfo/index.tsx
  src/components/mypage/userInfo/styles.ts
  src/pages/index.ts
  src/pages/mypage/index.tsx
  src/pages/mypage/styles.ts
  src/routes/index.ts
  src/styles/globalStyles.ts
  src/styles/layout.ts
Labels: enhancement

#21 [PR] 로그인 UI 구현
  src/assets/images/loginImage.jpg
  src/components/loginForm/index.tsx
  src/components/loginForm/styles.ts
  src/components/shared/Icon.tsx
  src/components/shared/StyledButton.ts
  src/pages/login/index.tsx
  src/styles/layout.ts
Labels: enhancement

#20 [PR] 코드 에디터 및 formData 세팅
  src/components/post/codeBox/index.tsx
  src/components/post/descriptonBox/index.tsx
  src/components/post/testCaseBox/index.tsx
  src/components/post/testCaseBox/styles.ts
  src/components/post/textareaField/index.tsx
  src/components/shared/CodeEditor.tsx
  src/components/shared/icon/styles.ts
  src/components/shared/modal/index.tsx
  src/components/shared/select/index.tsx
  src/components/shared/select/styles.ts
  src/hooks/post/useSetFormData.ts
  src/pages/post/index.tsx
  src/pages/post/right/index.tsx
  src/pages/post/right/styles.ts
  src/pages/post/styles.ts
  src/stores/post.ts
  src/types/post.ts
Labels: enhancement
